name: Automate project columns
on:
  pull_request:
    types: [opened, reopened]
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
    - name: Move new PRs to "In Progress"
      uses: alex-page/github-project-automation-plus@v0.8.3
      with:
        project: openim-powerful
        column: In Progress
        repo-token: ${{ secrets.GITHUB_TOKEN }}
